openapi: 3.0.0
info:
  title: Taskman
  description:
    'Taskman open documentations'
  version: 1.0.0
#  license:
#    name: MIT License
#    url: https://opensource.org/licenses/MIT
security:
  - TokenHeader: []
paths:
  /:
    get:
      description: 'Welcome'
      tags:
        - Welcome
      operationId: ping
      summary: 'Пример запроса'
      security: []
      responses:
        '200':
          description: OK