openapi: 3.0.0
info:
  title: Taskman
  description:
    'Taskman open documentations'
  version: 1.0.0
#  license:
#    name: MIT License
#    url: https://opensource.org/licenses/MIT
security:
  - TokenHeader: []
paths:
  /:
    get:
      description: 'Welcome'
      tags:
        - Welcome
      operationId: ping
      summary: 'Пример запроса'
      security: []
      responses:
        '200':
          description: OK
  /users:
    post:
      description: create user
      tags:
        - Users
      summary: Список пользоватей
      requestBody:
        $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        login:
          type: string
        password:
          type: string